version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y openssh-client
      - composer install --no-interaction --prefer-dist --optimize-autoloader
  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      - php artisan config:clear
      - echo "Fetching private key from Secrets Manager..."
      - aws secretsmanager get-secret-value --secret-id /ec2/deploy_key --query SecretString --output text > key.pem
      - chmod 400 key.pem
  build:
    commands:
      - echo "Build phase - nothing to build for Laravel"
  post_build:
    commands:
      - echo "Deploying to EC2..."
      - scp -i key.pem -o StrictHostKeyChecking=no -r * ec2-user@172.31.82.121:/var/www/html 

artifacts:
  files:
    - '**/*'
  discard-paths: no  